$(document).ready(function(){
	$("#view_course").click(function(){
		$("#show_table").append("<table class='container' id='course_table' border='1' style='width: 50%;'><tr><td>ظرفیت</td><td>روز ارائه</td><td>استاد</td><td>همنیاز</td><td>پیش نیاز</td><td>واحد</td><td>درس</td></tr></table>");
	});
	$("#add_course").click(function(){
		$("#show_table").html("");
		$("#show_table").append("<div id='info_text' class='input-group' style='height: 150px;position: fixed;top: 20%;left: 80%;font-family: 'B Nazanin''><div><input id='input_text1' type='text' class='form-control' placeholder='Course Name' aria-describedby='basic-addon1' style='width: 170px;margin-top: 10%;' maxlength='8' autofocus><label style='margin-top: 10%;'>&nbsp;&nbsp;:درس</label></div><div><input id='input_text2' type='text' class='form-control' placeholder='Unit' aria-describedby='basic-addon1' style='width: 170px;margin-top: 10%' maxlength='10'><label style='margin-top: 13%;'>&nbsp;&nbsp;:واحد</label></div><div ><input id='input_text2' type='text' class='form-control' placeholder='Pre Course' aria-describedby='basic-addon1' style='width: 170px;margin-top: 10%' maxlength='10'><label style='margin-top: 13%;'>&nbsp;&nbsp;:پیشنیاز</label></div><div><input id='input_text2' type='text' class='form-control' placeholder='Need Course' aria-describedby='basic-addon1' style='width: 170px;margin-top: 10%' maxlength='10'><label style='margin-top: 14%;'>&nbsp;&nbsp;:همنیاز</label></div><div><input id='input_text2' type='text' class='form-control' placeholder='Professor' aria-describedby='basic-addon1' style='width: 170px;margin-top: 10%' maxlength='10'><label style='margin-top: 14%;'>&nbsp;&nbsp;:استاد</label></div><div><input id='input_text2' type='Time' class='form-control' placeholder='Time' aria-describedby='basic-addon1' style='width: 170px;margin-top: 10%' maxlength='10'><label style='margin-top: 14%;'>&nbsp;&nbsp;:روز ارائه</label></div><div ><input id='input_text2' type='Password' class='form-control' placeholder='Password' aria-describedby='basic-addon1' style='width: 170px;margin-top: 10%' maxlength='10'><label style='margin-top: 14%;'>&nbsp;&nbsp;:ظرفیت</label></div><div class='btn-group' role='group'><button id='login_id' type='button' class='btn btn-default' style='width: 100px;margin-top: 10%'>ثبت اطلاعات درس</button></div></div>");
	});
});
	